[package]
name = "server"
version = "0.1.0"
authors = ["Lawrence Thorpe <lawrence@lawrencethorpe.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
dialoguer = "0.8.0"
get_if_addrs = "0.5.3"
scrap = "0.5"
structopt = "0.3.21"
utils = { path = "utils" }

[dev-dependencies]
criterion = "0.3.4"
image = "0.23.14"

[[bench]]
name = "image"
harness = false

[[bench]]
name = "compress"
harness = false
