[package]
name = "utils"
version = "0.1.0"
authors = ["Lawrence Thorpe <lawrence@lawrencethorpe.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
flate2 = "1.0.20"
get_if_addrs = "0.5.3"
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
