name: Build server

on:
  push:
    paths:
      - packages/server/**

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Strip debug symbols
        if: ${{ matrix.os != 'windows-latest' }}
        run: strip target/release/server
      - uses: actions/upload-artifact@v2
        with:
          path: target/release/
